import { AdminPreviewPage } from './AdminPreviewPage';

const productItems = [
  { icon: 'person_search', label: 'Người dùng hoạt động', description: 'Theo dõi số người dùng hoạt động theo ngày, tuần và tháng.' },
  { icon: 'ads_click', label: 'Sự kiện sản phẩm', description: 'Theo dõi các hành động quan trọng trong từng luồng sản phẩm.' },
  { icon: 'repeat', label: 'Quay lại sử dụng', description: 'Theo dõi tỷ lệ người dùng trở lại sau lần trải nghiệm đầu tiên.' },
];

const systemItems = [
  { icon: 'monitor_heart', label: 'Tình trạng dịch vụ', description: 'Theo dõi API, cơ sở dữ liệu, Redis và dịch vụ bên ngoài.' },
  { icon: 'pending_actions', label: 'Tác vụ nền', description: 'Theo dõi hàng đợi phân tích CV, phỏng vấn, email và thông báo.' },
  { icon: 'warning', label: 'Cảnh báo cần xử lý', description: 'Tập trung lỗi và sự cố đang ảnh hưởng đến người dùng.' },
];

export const UserBehaviorPreviewPage = () => <AdminPreviewPage groupLabel="Phân tích sản phẩm" title="Hành vi người dùng" description="Theo dõi cách người dùng khám phá và sử dụng các tính năng quan trọng của Arion." items={productItems} />;
export const FunnelPreviewPage = () => <AdminPreviewPage groupLabel="Phân tích sản phẩm" title="Phễu sử dụng" description="Xem người dùng rời đi ở bước nào từ đăng ký đến nhận kết quả." items={[{ icon: 'how_to_reg', label: 'Đăng ký', description: 'Tỷ lệ khách truy cập hoàn thành tạo tài khoản.' }, { icon: 'upload_file', label: 'Tạo dữ liệu đầu vào', description: 'Tỷ lệ tải CV hoặc chọn mẫu CV/JD.' }, { icon: 'summarize', label: 'Hoàn thành kết quả', description: 'Tỷ lệ nhận phân tích CV hoặc báo cáo phỏng vấn.' }]} />;
export const AiQualityPreviewPage = () => <AdminPreviewPage groupLabel="Phân tích sản phẩm" title="Chất lượng AI" description="Đánh giá độ ổn định và mức hữu ích của kết quả AI." items={[{ icon: 'thumb_up', label: 'Phản hồi hữu ích', description: 'Đánh giá trực tiếp của người dùng về kết quả AI.' }, { icon: 'refresh', label: 'Yêu cầu tạo lại', description: 'Tỷ lệ người dùng chạy lại do kết quả chưa phù hợp.' }, { icon: 'rule', label: 'Kết quả cần rà soát', description: 'Các phản hồi cần đội ngũ kiểm tra chất lượng.' }]} />;
export const SystemStatusPreviewPage = () => <AdminPreviewPage groupLabel="Vận hành hệ thống" title="Tình trạng hệ thống" description="Nắm tình trạng tổng thể của các dịch vụ và dependency quan trọng." items={systemItems} />;
export const QueuePreviewPage = () => <AdminPreviewPage groupLabel="Vận hành hệ thống" title="Tác vụ nền / Queue" description="Theo dõi xử lý bất đồng bộ để phát hiện hàng đợi chậm hoặc thất bại." items={[{ icon: 'manage_history', label: 'CV analysis', description: 'Hàng đợi phân tích và tối ưu CV.' }, { icon: 'record_voice_over', label: 'Interview analysis', description: 'Hàng đợi chấm điểm phiên phỏng vấn.' }, { icon: 'mark_email_read', label: 'Email & thông báo', description: 'Hàng đợi gửi email và thông báo tới người dùng.' }]} />;
export const ApiErrorsPreviewPage = () => <AdminPreviewPage groupLabel="Vận hành hệ thống" title="API & lỗi" description="Tập trung cảnh báo và liên kết điều tra lỗi của ứng dụng." items={[{ icon: 'warning', label: 'Lỗi mới', description: 'Các lỗi chưa được phân loại hoặc cần ưu tiên xử lý.' }, { icon: 'speed', label: 'Độ trễ API', description: 'Các API chậm ảnh hưởng đến trải nghiệm người dùng.' }, { icon: 'assignment_late', label: 'Sự cố cần xử lý', description: 'Sự cố tác động trực tiếp đến các luồng quan trọng.' }]} />;
export const AiCostPreviewPage = () => <AdminPreviewPage groupLabel="Vận hành hệ thống" title="Chi phí AI" description="Kiểm soát mức sử dụng và chi phí AI theo tính năng, model và thời gian." items={[{ icon: 'token', label: 'Token tiêu thụ', description: 'Token đầu vào và đầu ra theo từng luồng AI.' }, { icon: 'payments', label: 'Chi phí theo tính năng', description: 'Chi phí phân tích CV, tối ưu và phỏng vấn AI.' }, { icon: 'account_balance_wallet', label: 'Ngân sách', description: 'So sánh chi phí với ngưỡng ngân sách đã đặt.' }]} />;
export const ConfigurationPreviewPage = () => <AdminPreviewPage groupLabel="Cài đặt" title="Cấu hình hệ thống" description="Tập trung các cấu hình sản phẩm có thể điều chỉnh an toàn." items={[{ icon: 'tune', label: 'Quy tắc sản phẩm', description: 'Thiết lập giới hạn và hành vi mặc định.' }, { icon: 'credit_score', label: 'Giá & credit', description: 'Cấu hình mức credit cho từng tác vụ.' }, { icon: 'notifications_active', label: 'Cảnh báo vận hành', description: 'Quản lý ngưỡng cảnh báo và kênh nhận thông báo.' }]} />;
